### ISSUE TITLE
regarding the purpose of the `iframe` element

### ISSUE THREAD

**Issue by arlenpeiffer** [AristideBH/Marqueeck#4]
hey @AristideBH — super cool project! really digging it

had a quick question..  what's the purpose of the `<iframe>` element that appears just below the element with `data-marqueeck-ribbon`?

<img width="1840" alt="Screenshot 2024-07-21 at 4 42 23 PM" src="https://github.com/user-attachments/assets/6d4c8253-e5b6-41fe-ab2c-bc6aa4428f18">

**Comment by AristideBH** [comment]
Hi, thanks for your support !
From memory, that's how Sveltekit keeps track of the width of the marquee, using the `bind:offsetWidth` proprety. This is used to repeat the right number of elements to fill the marquee !

**Comment by arlenpeiffer** [comment]
aha! that makes sense — did some digging in the svelte docs and found the [bit about advanced bindings for dimensions](https://learn.svelte.dev/tutorial/dimensions). super cool.

thanks so much for the heads up on this and again, great work on the project! i'll go ahead and close out this issue :)
