### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by matteocontrini** [AristideBH/Marqueeck#5]
Hi,

I'm using this library with Svelte 5, and it seems to work fine.

However, it can't be installed without forcing the installation because of the peer dependency of Svelte 4.

Would it be possible to have a release that also includes Svelte 5 in the peer dependencies?

Thanks!

**Comment by AristideBH** [comment]
Hello, 
Thanks for your interest !
Note taken, I will try to update the dependency tree to include Svelte 5 soon
If time allows it, I might rework the complete component logic with runes !

**Comment by AristideBH** [comment]
Hey, 
Just updated the package dependencies, including the Svelte 5 requirement, in the 0.5.1 version.
No specific rewrite with runes yet !

**Comment by matteocontrini** [comment]
Thank you!
